# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t0Mv-Ivo1_GH9Te1LXz-rVJ_sodA4r_c
"""

import pandas as pd
df = pd.DataFrame({
    'Familyasi' : [ 'ABDUXAKIMOV', 'AZIZIBLOYEV ', 'DO‘LTABOYEV', ' ESHBOYEV', 'KOMILOVA', 'MADAMINJONOV', 'MAMADALIYEV', 'MAMATVALIYEV', 'MIRZAHAMIDOV', ' MUHAMMADALIYEV', 'NE’MATOVA' ],
       'Ismi'  : [ 'XURSANDBEK', 'HOJIAKBAR', 'MUHAMMADJON', 'ILXOM', 'DINORA', 'BAXTIYORJON', 'ZIKRULLO', 'DILSHODBEK', 'JALOLIDDIN ', 'ABDULLO ', 'DILDORAXON'   ],
      'Yoshi' : [  '19', '19', '19', '19', '19', '19', '19', '19', '19', '19', '19'  ],
         'Kursi' : [  '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2'   ]

})
print(df)

df.to_excel('malumot.xlsx', index=False, sheet_name='Sheet1')
